// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunHTTPX(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:string,arg9:boolean,arg10:number,arg11:boolean,arg12:string,arg13:boolean,arg14:string,arg15:Array<string>,arg16:Array<string>):Promise<string>;
